### ISSUE TITLE
Additional methods for solving Dynamic Programming problems

### ISSUE THREAD

**Issue by azev77** [mossr/BeautifulAlgorithms.jl#1]
Hi and thank you for this package. 
The algorithms are indeed very beautiful! 

I find your [value_iteration](https://github.com/mossr/BeautifulAlgorithms.jl/blob/master/src/value_iteration.jl).jl especially useful.
Is there a chance you can include some other common algorithms for solving dynamic programming problems? 
A [recent paper](https://lmaliar.ws.gc.cuny.edu/files/2019/01/CEPR-DP13210.pdf) provides 7 common algorithms to solve a routine dynamic programming problem: 

![image](https://user-images.githubusercontent.com/7883904/105931920-16a10680-601a-11eb-9fc2-1bb9f155629c.png)
(the AR process will be discretized into a discrete state Markov Chain)

Optimality conditions: 
![image](https://user-images.githubusercontent.com/7883904/105932008-39cbb600-601a-11eb-85bb-3456b66cc1a6.png)

7 standard methods: 
![image](https://user-images.githubusercontent.com/7883904/105932035-44864b00-601a-11eb-824c-9bd962605fb8.png)

![image](https://user-images.githubusercontent.com/7883904/105932064-4b14c280-601a-11eb-987f-e8dd41a836b1.png)

![image](https://user-images.githubusercontent.com/7883904/105932074-4f40e000-601a-11eb-9b3a-103083d9df91.png)

![image](https://user-images.githubusercontent.com/7883904/105932086-5536c100-601a-11eb-946f-52f11886bec6.png)

![image](https://user-images.githubusercontent.com/7883904/105932108-5c5dcf00-601a-11eb-8b01-236dca5eb9d0.png)

![image](https://user-images.githubusercontent.com/7883904/105932123-6253b000-601a-11eb-84f5-d7f8c687d9af.png)

![image](https://user-images.githubusercontent.com/7883904/105932134-68499100-601a-11eb-9b62-055257f40adb.png)

**Comment by mossr** [comment]
Those are concise! I don't have plans to implement them at the moment (but am open to PRs).

I think you'd find the following textbook useful to you (which is where I got the value iteration algorithm from): https://algorithmsbook.com/

Specifically the combination of algorithms 7.2, 7.7, and 7.8 of [Chapter 7: Exact Solution Methods](https://algorithmsbook.com/files/chapter-7.pdf).
