### ISSUE TITLE
code images corrupted

### ISSUE THREAD

**Issue by SimonEnsemble** [mossr/BeautifulAlgorithms.jl#2]
very cool!
but to me, many of the images appear corrupted.

![image](https://user-images.githubusercontent.com/30643894/122436699-e36dfe00-cf4d-11eb-858f-b6a7971fb008.png)

**Comment by mossr** [comment]
Yeah...SVG is funny sometimes. Is this on mobile by any chance?

**Comment by SimonEnsemble** [comment]
:eyes: 
this is on Firefox, Linux Mint.

**Comment by mreppen** [comment]
I experience the same thing (Firefox, Linux). But when opening the image in a separate tab, it displays properly.

The problem only appears on line breaks

**Comment by shenlebantongying** [comment]
It also  happens on Firefox, Windows10.

left-> firefox
right -> chrome

![firefox_TTAZ4tN9Rp](https://user-images.githubusercontent.com/20123683/125115390-453b0700-e0b9-11eb-80ef-8a1dca3784ed.png)

**Comment by agucova** [comment]
I'm also getting on Firefox Dev. Edition latest. Not ideal, but is it possible to switch to PNGs?

**Comment by NHDaly** [comment]
> Yeah...SVG is funny sometimes. Is this on mobile by any chance?

And yeah, to add another data point, for me on Android mobile many of the characters don't render:

![Screenshot_20210711-101943](https://user-images.githubusercontent.com/1582097/125198832-8f46f880-e231-11eb-8fb2-fd954e35bb32.png)

**Comment by NHDaly** [comment]
(which of course is related to the fact that the original source doesn't contains characters android won't display as well):
![Screenshot_20210711-102115](https://user-images.githubusercontent.com/1582097/125198909-dcc36580-e231-11eb-8b42-a18f6b43580f.png)


The suggestion to somehow convert the sources to pixels before uploading the images would be nice, yeah.

**Comment by mossr** [comment]
Simple answer was just to use the PNGs I was already creating (instead of the SVGs). Fixed via 2d2862486aa65098e1d1989571fe912caa3af9fe
